# input 
input-conf=/storage/emulated/0/Android/media/is.xyz.mpv/input.conf  

vo=gpu gpu-context=android profile=opengl-hq hwdec=mediacodec-copy

# comment basic script and uncomment load more script if use more script 

# basic script
scripts=/storage/emulated/0/Android/media/is.xyz.mpv/scripts/hello.lua

# load more script : 
# scripts=/storage/emulated/0/Android/media/is.xyz.mpv/scripts/hello.lua:/storage/emulated/0/Android/media/is.xyz.mpv/scripts/resolution.lua

